name: ci
'on':
  pull_request:
    branches:
      - main

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: set nx affected shas
        uses: nrwl/nx-set-shas@v3

      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: yarn

      - name: Install deps
        run: yarn --immutable

      - name: Lint
        run: yarn nx affected --target=lint

      - name: Test
        run: yarn nx affected --target=test
