name: ci
'on':
  release:
    types: [published]

jobs:
  deploy-production:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: yarn

      - name: Install deps
        run: yarn --immutable

      - name: Build library
        run: yarn nx build react-column-view

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: yarn semantic-release

      - name: Publish package to NPM 📦
        run: npm publish ./dist/libs/react-column-view
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
